# Generated by Django 2.2.5 on 2019-11-30 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_extra',
            name='organization',
        ),
    ]
