# Generated by Django 2.2.5 on 2019-12-01 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_player_one', models.IntegerField(default=0)),
                ('result_player_two', models.IntegerField(default=0)),
                ('game', models.CharField(choices=[('fifa', 'FIFA'), ('mk', 'Mortal Kombat')], default='fifa', max_length=15)),
                ('player_one', models.ForeignKey(on_delete=None, related_name='match_related', to=settings.AUTH_USER_MODEL)),
                ('player_two', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
