# Generated by Django 2.2.5 on 2019-12-01 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Match', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No name', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='match_admin',
            field=models.ForeignKey(default=1, on_delete=None, related_name='admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_one',
            field=models.ForeignKey(default=1, on_delete=None, related_name='player_one', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='player_two',
            field=models.ForeignKey(default=1, on_delete=None, related_name='player_two', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TournamentParticipants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Match.Tournament')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Match.Tournament'),
        ),
    ]
