# Generated by Django 2.2.5 on 2019-12-08 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Match', '0002_auto_20191201_0435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentparticipants',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentparticipants',
            name='user',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='match_admin',
            new_name='admin',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player_one',
        ),
        migrations.RemoveField(
            model_name='match',
            name='player_two',
        ),
        migrations.RemoveField(
            model_name='match',
            name='result_player_one',
        ),
        migrations.RemoveField(
            model_name='match',
            name='result_player_two',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournament',
        ),
        migrations.AddField(
            model_name='match',
            name='participant1Score',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='participant2Score',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='match',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='game',
            field=models.CharField(choices=[('FIFA', 'FIFA'), ('SMASH', 'Smash')], default='FIFA', max_length=10),
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.DeleteModel(
            name='TournamentParticipants',
        ),
    ]
