# Generated by Django 2.2.5 on 2019-12-11 09:03

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Match', '0003_auto_20191208_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='participant1Score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='participant2Score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='participants',
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(default=datetime.date(2019, 12, 11)),
        ),
        migrations.CreateModel(
            name='MatchEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.BigIntegerField(default=1)),
                ('match', models.ForeignKey(on_delete=None, to='Match.Match')),
                ('participant', models.ForeignKey(on_delete=None, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
