# Generated by Django 2.2.5 on 2019-12-11 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Match', '0004_auto_20191211_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='name',
            field=models.CharField(default='Match', max_length=30),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
